### ISSUE TITLE
Make error messages a bit more meanigful

### ISSUE THREAD

**Issue by grinapo** [systemd/casync#52] opened 2017-07-05 06:23 UTC
`$ /oldzfs/test$ casync make sznep.caidx /oldzfs/snap-22\:24`
**Failed to run synchronizer: Invalid argument**
Which argument? How invalid?

**Comment by poettering** [comment] 2017-07-24 11:24
Duplicate of #44

**Closed by poettering** 2017-07-24 11:24 UTC
